[project]
name = "code-expert-team"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai",
    "crewai-tools",
]

[project.scripts]
code_expert_team = "code_expert_team.main:run"

[tool.setuptools.packages.find]
where = ["src"]
