#!/usr/bin/env python3
"""Export standardized delivery ZIP for external sending.

Usage:
    python scripts/export_case_delivery_zip.py --case-dir cases/demo_phase
    python scripts/export_case_delivery_zip.py --case-dir cases/demo_phase --json
"""

from __future__ import annotations

import argparse
import json
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[1]
_CSV_CLEANING = _REPO_ROOT / "notebooks" / "csv_cleaning"
if str(_CSV_CLEANING) not in sys.path:
    sys.path.insert(0, str(_CSV_CLEANING))

from case_delivery_bundle import build_case_delivery_bundle  # noqa: E402


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _readme(case_id: str, case_dir_rel: str) -> str:
    return (
        f"# Delivery package · {case_id}\n\n"
        f"Case: `{case_dir_rel}`\n\n"
        "## Contents\n\n"
        "- `cleaned/` — cleaned CSV outputs\n"
        "- `reports/` — JSON/MD quality reports and stats\n"
        "- `delivery_signoff.md` — internal signoff record\n\n"
        "Generated by `scripts/export_case_delivery_zip.py` (operator export; not customer SaaS).\n"
    )


def export_case_delivery_zip(
    case_dir: Path,
    *,
    repo_root: Path | None = None,
    refresh_bundle: bool = True,
) -> dict[str, Any]:
    root = repo_root or _REPO_ROOT
    case_dir = case_dir.resolve()
    case_dir_rel = case_dir.relative_to(root).as_posix()

    intake_path = case_dir / "intake.json"
    case_id = case_dir.name
    if intake_path.is_file():
        try:
            intake = json.loads(intake_path.read_text(encoding="utf-8"))
            case_id = str(intake.get("case_id") or case_id)
        except (OSError, json.JSONDecodeError):
            pass

    if refresh_bundle:
        bundle = build_case_delivery_bundle(case_dir)
        if not bundle.get("ok"):
            return {
                "ok": False,
                "message": bundle.get("message", "build_case_delivery_bundle failed"),
                "case_dir": case_dir_rel,
            }

    delivery_dir = case_dir / "delivery"
    delivery_dir.mkdir(parents=True, exist_ok=True)
    zip_name = f"{case_id}_delivery_{_utc_stamp()}.zip"
    zip_path = delivery_dir / zip_name

    include_paths: list[tuple[Path, str]] = []
    cleaned = case_dir / "cleaned"
    if cleaned.is_dir():
        for path in sorted(cleaned.glob("*")):
            if path.is_file():
                include_paths.append((path, f"cleaned/{path.name}"))

    reports = case_dir / "reports"
    if reports.is_dir():
        for path in sorted(reports.glob("*")):
            if path.is_file() and path.name != "automation_run_log.json":
                include_paths.append((path, f"reports/{path.name}"))

    signoff = case_dir / "delivery_signoff.md"
    if signoff.is_file():
        include_paths.append((signoff, "delivery_signoff.md"))

    if not include_paths:
        return {"ok": False, "message": "no delivery artifacts to zip", "case_dir": case_dir_rel}

    readme_rel = "README_delivery.md"
    readme_content = _readme(case_id, case_dir_rel)

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(readme_rel, readme_content)
        for src, arc in include_paths:
            zf.write(src, arcname=arc)

    return {
        "ok": True,
        "case_id": case_id,
        "case_dir": case_dir_rel,
        "zip_path": zip_path.relative_to(root).as_posix(),
        "artifact_count": len(include_paths) + 1,
        "message": f"delivery zip written: {zip_path.relative_to(root).as_posix()}",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export case delivery ZIP package.")
    parser.add_argument("--case-dir", required=True, type=Path)
    parser.add_argument("--no-refresh-bundle", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    case_dir = args.case_dir
    if not case_dir.is_absolute():
        case_dir = _REPO_ROOT / case_dir

    result = export_case_delivery_zip(
        case_dir,
        refresh_bundle=not args.no_refresh_bundle,
    )
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(result.get("message", ""))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
