"""Pydantic schemas for structured errors and core node outputs."""

from core.schemas.errors import StructuredError, UnifiedErrorEnvelope
from core.schemas.outputs import (
    HealthCheckResult,
    IngestBatchResult,
    LGStateEnvelope,
    RagAnswerResult,
    RagSourceItem,
    RetrieveSmokeResult,
    VerifyBatchResult,
)
from core.schemas.phase6_5_entities import (
    Delivery,
    Invoice,
    Job,
    Lead,
    Order,
    Payment,
    ReplayEvent,
    RequirementProfile,
    Run,
    SkillCard,
    SkillRun,
    entity_model_for_type,
)
from core.schemas.phase6_5_events import EventEnvelope, build_event
from core.schemas.wave6_manifest import (
    ManifestBillingUnits,
    ManifestContentSummary,
    ManifestEnrichment,
    ManifestEnrichmentSignals,
    ManifestRow,
    ManifestV20,
    WAVE6_BILLING_TABLE_VERSION_DEFAULT,
    WAVE6_ENRICHMENT_SCHEMA_VERSION,
    WAVE6_ENVELOPE_SCHEMA_VERSION,
    WAVE6_MANIFEST_VERSION,
    Wave6ManifestJobRecord,
)

__all__ = [
    "StructuredError",
    "UnifiedErrorEnvelope",
    "HealthCheckResult",
    "IngestBatchResult",
    "VerifyBatchResult",
    "RetrieveSmokeResult",
    "RagAnswerResult",
    "RagSourceItem",
    "LGStateEnvelope",
    "Lead",
    "RequirementProfile",
    "Order",
    "Job",
    "Run",
    "Delivery",
    "Invoice",
    "Payment",
    "SkillCard",
    "SkillRun",
    "ReplayEvent",
    "entity_model_for_type",
    "EventEnvelope",
    "build_event",
    "ManifestBillingUnits",
    "ManifestContentSummary",
    "ManifestEnrichment",
    "ManifestEnrichmentSignals",
    "ManifestRow",
    "ManifestV20",
    "WAVE6_BILLING_TABLE_VERSION_DEFAULT",
    "WAVE6_ENRICHMENT_SCHEMA_VERSION",
    "WAVE6_ENVELOPE_SCHEMA_VERSION",
    "WAVE6_MANIFEST_VERSION",
    "Wave6ManifestJobRecord",
]
