"""Generate Fiverr deliverables: cleaned Excel + HTML report from pipeline JSON."""
import json, csv
from pathlib import Path
from datetime import datetime

def generate_html_report(report: dict, output_path: Path) -> None:
    """Generate a professional HTML cleaning report from pipeline JSON."""
    pm = report.get("product_metrics", {})
    summary = report.get("summary", {})
    stats = report.get("stats", {})
    meta = report.get("meta", {})
    
    total_rows = pm.get("total_rows", 0)
    accepted = pm.get("accepted_rows", 0)
    rejected = pm.get("rejected_rows", 0)
    dupes = pm.get("duplicate_rows_found", 0)
    miss_before = sum(s.get("missing_before", 0) for s in stats.get("missing_value_stats", []))
    miss_after = sum(s.get("missing_after", 0) for s in stats.get("missing_value_stats", []))
    fmt_fixes = pm.get("format_fixes_applied", {})
    clean_rate = round(accepted / total_rows * 100, 1) if total_rows else 0
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Build column detail rows
    col_rows = ""
    for s in stats.get("missing_value_stats", []):
        field = s["field"]
        mb = s["missing_before"]
        ma = s["missing_after"]
        rb = f"{s['rate_before']*100:.1f}%"
        ra = f"{s['rate_after']*100:.1f}%"
        strategy = "Median/Mode fill" if mb > ma else "Flagged"
        col_rows += f"<tr><td>{field}</td><td>{mb}</td><td>{ma}</td><td>{rb}</td><td>{ra}</td><td>{strategy}</td></tr>\n"
    
    # Before/After metrics
    def fmt(n): return f"{n:,}"
    
    fmt_unparseable = pm.get("anomaly_count_by_rule", {}).get("format_unparseable", 0)
    fmt_range = pm.get("anomaly_count_by_rule", {}).get("numeric_out_of_range", 0)
    text_trimmed = fmt_fixes.get("text_trimmed", 0)
    
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Data Cleaning Report</title>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }}
h1 {{ color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
.summary {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }}
.metric {{ display: inline-block; text-align: center; padding: 15px 30px; margin: 5px; background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
.metric .num {{ font-size: 32px; font-weight: bold; color: #e94560; }}
.metric .label {{ font-size: 14px; color: #666; }}
table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
th {{ background: #1a1a2e; color: white; }}
tr:hover {{ background: #f5f5f5; }}
.before {{ background: #fff3cd; }}
.after {{ background: #d4edda; }}
.footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }}
</style></head><body>
<h1>📊 Data Cleaning Report</h1>
<p><strong>Service:</strong> Professional Excel/CSV Data Cleaning</p>
<p><strong>Profile:</strong> {meta.get('cleaning_profile_id', 'N/A')}</p>
<p><strong>Date:</strong> {now}</p>

<div class="summary">
<h3>Summary</h3>
<div class="metric"><div class="num">{fmt(total_rows)}</div><div class="label">Rows Processed</div></div>
<div class="metric"><div class="num">{fmt(dupes)}</div><div class="label">Duplicates Removed</div></div>
<div class="metric"><div class="num">{fmt(rejected)}</div><div class="label">Rows Rejected</div></div>
<div class="metric"><div class="num">{clean_rate}%</div><div class="label">Clean Rate</div></div>
</div>

<h3>Issues Found & Fixed</h3>
<table>
<tr><th>Issue Type</th><th>Count</th><th>Resolution</th></tr>
<tr><td>Missing Values (nulls)</td><td>{fmt(miss_before)}</td><td>Statistical imputation / flagged</td></tr>
<tr><td>Duplicates (PK)</td><td>{fmt(dupes)}</td><td>Deduplicated (keep latest)</td></tr>
<tr><td>Format Issues</td><td>{fmt(fmt_unparseable)}</td><td>Flagged for review</td></tr>
<tr><td>Range Anomalies</td><td>{fmt(fmt_range)}</td><td>Flagged for review</td></tr>
<tr><td>Text Trimmed</td><td>{fmt(text_trimmed)}</td><td>Whitespace removed</td></tr>
</table>

<h3>Before vs After</h3>
<table>
<tr><th>Metric</th><th class="before">Before</th><th class="after">After</th></tr>
<tr><td>Total Rows</td><td class="before">{fmt(total_rows)}</td><td class="after">{fmt(accepted)}</td></tr>
<tr><td>Null Values</td><td class="before">{fmt(miss_before)}</td><td class="after">{fmt(miss_after)}</td></tr>
<tr><td>Duplicates</td><td class="before">{fmt(dupes)}</td><td class="after">0</td></tr>
</table>

<h3>Column Detail</h3>
<table>
<tr><th>Column</th><th>Missing Before</th><th>Missing After</th><th>Rate Before</th><th>Rate After</th><th>Strategy</th></tr>
{col_rows}
</table>

<div class="footer">
<p>Generated by Data Cleaning Pipeline | Powered by MCP-Excel</p>
<p>This report demonstrates automated data quality improvement.</p>
</div>
</body></html>"""
    
    output_path.write_text(html, encoding="utf-8")


def csv_to_excel(csv_path: Path, xlsx_path: Path) -> None:
    """Convert cleaned CSV to formatted Excel."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    
    wb = Workbook()
    ws = wb.active
    ws.title = "Cleaned Data"
    
    # Read CSV
    with csv_path.open(encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    
    if not rows:
        return
    
    headers = rows[0]
    data = rows[1:]
    
    # Header style
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="1A1A2E", end_color="1A1A2E", fill_type="solid")
    thin_border = Border(
        bottom=Side(style="thin", color="DDDDDD"),
    )
    
    # Write headers
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")
    
    # Write data
    for row_idx, row in enumerate(data, 2):
        for col_idx, value in enumerate(row, 1):
            # Try to parse numbers
            try:
                value = float(value)
                if value == int(value):
                    value = int(value)
            except (ValueError, TypeError):
                pass
            ws.cell(row=row_idx, column=col_idx, value=value)
    
    # Auto-fit column widths
    for col_idx in range(1, len(headers) + 1):
        max_len = len(str(headers[col_idx - 1]))
        for row_idx in range(2, min(len(data) + 2, 52)):  # Sample first 50 rows
            val = ws.cell(row=row_idx, column=col_idx).value
            if val:
                max_len = max(max_len, min(len(str(val)), 40))
        ws.column_dimensions[get_column_letter(col_idx)].width = max_len + 3
    
    # Freeze header
    ws.freeze_panes = "A2"
    
    # Auto-filter
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}{len(data) + 1}"
    
    wb.save(xlsx_path)


if __name__ == "__main__":
    import sys
    
    TEST_DIR = Path(__file__).resolve().parent
    OUTPUT_DIR = TEST_DIR / "output"
    DELIVERABLES_DIR = TEST_DIR / "deliverables"
    DELIVERABLES_DIR.mkdir(exist_ok=True)
    
    # Process all report JSONs
    for json_path in sorted(OUTPUT_DIR.glob("report_*.json")):
        dataset_name = json_path.stem.replace("report_", "")
        print(f"\n=== Generating deliverables for: {dataset_name} ===")
        
        # Load report
        report = json.loads(json_path.read_text(encoding="utf-8"))
        
        # 1. HTML report
        html_path = DELIVERABLES_DIR / f"report_{dataset_name}.html"
        generate_html_report(report, html_path)
        print(f"  HTML report: {html_path} ({html_path.stat().st_size:,} bytes)")
        
        # 2. Excel from cleaned CSV
        csv_path = OUTPUT_DIR / f"cleaned_{dataset_name}.csv"
        if csv_path.exists():
            xlsx_path = DELIVERABLES_DIR / f"cleaned_{dataset_name}.xlsx"
            csv_to_excel(csv_path, xlsx_path)
            print(f"  Excel file:  {xlsx_path} ({xlsx_path.stat().st_size:,} bytes)")
        
        # 3. Copy JSON report
        import shutil
        json_out = DELIVERABLES_DIR / f"report_{dataset_name}.json"
        shutil.copy2(json_path, json_out)
        print(f"  JSON report: {json_out}")
    
    print(f"\n✅ All deliverables → {DELIVERABLES_DIR}")
    print(f"   Files: {len(list(DELIVERABLES_DIR.iterdir()))}")
